n,m = map(int,input().split())
arr = list(map(int,input().split()))
A = set(map(int,input().split()))
B = set(map(int,input().split()))
a =sum(i in A for i in arr)
b =sum(i in B for i in arr)
print(a-b)
